[package]
name = "mal"
version = "0.1.0"
authors = ["Jay Mundrawala <jay@thechamberofunderstanding.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
itertools = "0.10.0"
